### ISSUE TITLE
s{lib/WebServices}{lib/WebService}

### ISSUE THREAD

**Issue by tbrowder** [fayland/perl6-WebService-GitHub#6]
confuses zef installer--inconsistent names in META.info and repository name and module files:

is it "WebService" OR "WebServices"

**Comment by fayland** [comment]
yes, I'll do a fix now. it should be WebService.

**Comment by fayland** [comment]
fixed. Thanks!

**Comment by tbrowder** [comment]
thank you--that was quick!
